"""Graph node models for the unified investigation graph.

Identifiers should be UUIDs generated by the caller. Timestamps default to UTC
instants so the schema stays minimal without forcing downstream code to supply
audit metadata manually.
"""

from __future__ import annotations

from datetime import datetime, timezone
from uuid import UUID

from pydantic import BaseModel, Field


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class GraphEntityBase(BaseModel):
    id: UUID
    created_at: datetime = Field(default_factory=_utcnow)
    updated_at: datetime = Field(default_factory=_utcnow)


class Case(GraphEntityBase):
    pass


class Person(GraphEntityBase):
    pass


class Officer(GraphEntityBase):
    pass


class Unit(GraphEntityBase):
    pass


class Court(GraphEntityBase):
    pass


class Location(GraphEntityBase):
    pass


class Act(GraphEntityBase):
    pass


class Section(GraphEntityBase):
    pass


class CrimeHead(GraphEntityBase):
    pass


class CrimeSubHead(GraphEntityBase):
    pass


class Evidence(GraphEntityBase):
    pass


class Dependency(GraphEntityBase):
    pass


class ClockInstance(GraphEntityBase):
    pass


class EscalationEvent(GraphEntityBase):
    pass


class ConversationLog(GraphEntityBase):
    pass