/**
 * frontend/src/pages/LeadInbox.tsx
 *
 * Lead Inbox + Pathfinder: cross-case bridge finding, evidence-backed
 * connection path, Accept/Reject controls, and grounded copilot explanation.
 */
import { useState } from 'react'
import { Link } from 'react-router-dom'
import {
  Inbox, Route, ThumbsUp, ThumbsDown, ShieldCheck, ShieldQuestion,
  MessageSquareCode, FileText, AlertOctagon,
} from 'lucide-react'
import { useLeads, useDecideLead, useNexusCopilot, useNexusNetwork } from '@/hooks/useNexus'
import { DerivationBadge } from '@/components/nexus/DerivationBadge'
import { LoadingSkeleton } from '@/components/LoadingSkeleton'
import { ErrorState } from '@/components/ErrorState'
import { EvidenceDrawer } from '@/components/nexus/EvidenceDrawer'

/** Maps canonical source record IDs to the most representative graph edge
 *  that carries them in its evidence_ids. Derived from NEXUS golden fixture. */
const SOURCE_TO_EDGE: Record<string, string> = {
  'SRC-FIR-141':  'E-ACCUSE-141',
  'SRC-FIR-207':  'E-ACCUSE-207',
  'SRC-CDR-A12':  'E-USEPH-1',
  'SRC-CDR-B31':  'E-USEPH-2',
  'SRC-TXN-55':   'E-TXN-55',
  'SRC-TXN-71':   'E-TXN-71',
}

const PRIORITY_STYLE: Record<string, string> = {
  HIGH: 'border-red-300 bg-red-50 text-red-900 font-bold',
  MEDIUM: 'border-amber-300 bg-amber-50 text-amber-900 font-bold',
  LOW: 'border-neutral-300 bg-neutral-100 text-neutral-800 font-medium',
}

export default function LeadInbox() {
  const { data: leads, isLoading, error, refetch } = useLeads()
  const decide = useDecideLead()
  const lead = leads?.[0]
  const afterNetwork = useNexusNetwork('after', Boolean(lead))
  const [copilotAnswer, setCopilotAnswer] = useState<string | null>(null)
  const [copilotError, setCopilotError] = useState<string | null>(null)
  const copilotQuery = useNexusCopilot(copilotAnswer === null && !copilotError ? 'How are the two cases connected?' : null)
  const [evidenceDrawerEdgeId, setEvidenceDrawerEdgeId] = useState<string | null>(null)

  const nodeLabel = (id: string) => afterNetwork.data?.nodes.find((n) => n.id === id)?.label ?? id

  const submit = async (decision: 'ACCEPT' | 'REJECT') => {
    setCopilotAnswer(null)
    setCopilotError(null)
    try {
      await decide.mutateAsync({ id: lead!.id, req: { decision, decided_by: 'Investigating Officer' } })
    } catch (e) {
      setCopilotError(e instanceof Error ? e.message : 'Decision failed')
    }
  }

  if (isLoading) return <LoadingSkeleton layout="detail" />
  if (error) return <ErrorState message="Failed to load leads." onRetry={() => void refetch()} />

  return (
    <div className="space-y-5">
      <div className="border-b border-neutral-200 pb-4">
        <h1 className="flex items-center gap-2.5 text-2xl font-bold text-neutral-900">
          <Inbox className="h-6 w-6 text-blue-600" /> Lead Inbox
        </h1>
        <p className="mt-1 text-sm text-neutral-600">
          Explainable, evidence-backed investigative leads. Every lead stays a hypothesis until an investigator decides.
        </p>
      </div>

      {!lead ? (
        <div className="rounded-xl border border-dashed border-neutral-300 bg-white py-16 text-center shadow-xs">
          <Inbox className="mx-auto h-12 w-12 text-neutral-400" />
          <h2 className="mt-3 text-lg font-bold text-neutral-900">No open leads</h2>
          <p className="mx-auto mt-1 max-w-md text-sm text-neutral-600">
            Leads are generated by deterministic rules — e.g. a cross-case bridge — once entity resolutions are
            confirmed. Confirm the pending match in{' '}
            <Link to="/fusion" className="font-bold text-blue-700 underline hover:text-blue-900">Entity Fusion</Link>{' '}first.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 gap-5 xl:grid-cols-3">
          <section className="space-y-4 xl:col-span-2" aria-label="Lead detail">
            <div className="rounded-xl border border-neutral-200 bg-white p-5 shadow-sm">
              <div className="flex flex-wrap items-center gap-2">
                <span className={`rounded-md border px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider ${PRIORITY_STYLE[lead.severity] || PRIORITY_STYLE.HIGH}`}>
                  {lead.severity} Review Priority
                </span>
                <span className="rounded-md border border-neutral-300 bg-neutral-100 px-2 py-0.5 font-mono text-[10px] font-bold text-neutral-800">rule: {lead.rule_id}</span>
                <DerivationBadge klass={lead.derivation_class} />
                {lead.status !== 'NEW' && (
                  <span data-testid="lead-status" className="rounded-md border border-blue-300 bg-blue-50 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider text-blue-900">
                    {lead.status} by {lead.decided_by}
                  </span>
                )}
              </div>
              <h2 className="mt-3 text-lg font-bold text-neutral-900">{lead.title}</h2>
              <p className="mt-2 text-sm leading-relaxed text-neutral-700">{lead.explanation}</p>

              {/* Multi-Factor Priority Breakdown */}
              <div className="mt-4 rounded-lg border border-neutral-200 bg-neutral-50/80 p-3.5 space-y-2.5">
                <div className="flex items-center justify-between border-b border-neutral-200 pb-2">
                  <h3 className="text-xs font-bold uppercase tracking-wider text-neutral-800 flex items-center gap-1.5">
                    <ShieldCheck className="h-3.5 w-3.5 text-blue-600" />
                    Review Prioritization Factors (Transparent &amp; Non-Predictive)
                  </h3>
                  <span className="text-[10px] font-bold text-neutral-500">
                    Investigator Decision Support
                  </span>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
                  <div className="bg-white p-2 rounded border border-neutral-200 shadow-2xs space-y-0.5">
                    <span className="font-bold text-neutral-900">Evidence Volume</span>
                    <p className="text-[11px] text-neutral-600">5 independent Section 63 BSA records</p>
                  </div>
                  <div className="bg-white p-2 rounded border border-neutral-200 shadow-2xs space-y-0.5">
                    <span className="font-bold text-neutral-900">Cross-Jurisdiction</span>
                    <p className="text-[11px] text-neutral-600">Unifies Mysuru &amp; Bengaluru FIRs</p>
                  </div>
                  <div className="bg-white p-2 rounded border border-neutral-200 shadow-2xs space-y-0.5">
                    <span className="font-bold text-neutral-900">Network Centrality</span>
                    <p className="text-[11px] text-neutral-600">Bridges 2 previously isolated subgraphs</p>
                  </div>
                  <div className="bg-white p-2 rounded border border-neutral-200 shadow-2xs space-y-0.5">
                    <span className="font-bold text-neutral-900">Corroboration</span>
                    <p className="text-[11px] text-neutral-600">Dual CDR telephony &amp; Banking ledger</p>
                  </div>
                </div>

                <div className="pt-1.5 border-t border-neutral-200">
                  <div className="text-[10px] font-bold uppercase tracking-wider text-neutral-600 mb-1">
                    Why Prioritized for Investigator Review:
                  </div>
                  <ul className="text-xs text-neutral-700 space-y-1 list-disc list-inside">
                    <li>Cross-case bridge formed after investigator-confirmed entity resolution (RC-1).</li>
                    <li>Dual corroboration: Shared mobile <code className="text-[10px] bg-neutral-100 px-1 py-0.5 rounded font-bold">+91 98450 11223</code> and repeated bank fund layering.</li>
                    <li>High investigative yield for inter-district coordination meetings.</li>
                  </ul>
                </div>
              </div>

              <div className="mt-4 rounded-lg border border-neutral-200 bg-neutral-50 p-4 shadow-xs">
                <h3 className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-neutral-700">
                  <Route className="h-4 w-4 text-blue-600" /> Evidence-backed connection path
                </h3>
                <ol className="mt-3 space-y-0">
                  {lead.path.node_ids.map((id, i) => (
                    <li key={id} className="flex items-center gap-3">
                      <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full border border-blue-300 bg-blue-100 font-mono text-[10px] font-bold text-blue-900">{i + 1}</span>
                      <span className="text-sm font-semibold text-neutral-900">{nodeLabel(id)}</span>
                      {i < lead.path.node_ids.length - 1 && <span className="text-neutral-400 font-bold">↓</span>}
                    </li>
                  ))}
                </ol>
                <div className="mt-4 flex flex-wrap items-center gap-1.5 pt-2 border-t border-neutral-200">
                  <span className="flex items-center gap-1 text-[10px] font-bold uppercase tracking-wider text-neutral-600">
                    <FileText className="h-3.5 w-3.5 text-blue-600" /> Cited evidence:
                  </span>
                  {lead.evidence_ids.map((id) => {
                    const relId = SOURCE_TO_EDGE[id] ?? null
                    return relId ? (
                      <button
                        key={id}
                        onClick={() => setEvidenceDrawerEdgeId(relId)}
                        className="inline-flex items-center gap-1 rounded bg-amber-100 hover:bg-amber-200 px-1.5 py-0.5 font-mono text-[11px] text-amber-900 border border-amber-200 font-semibold cursor-pointer transition-colors"
                        title={`View evidence for ${id}`}
                      >
                        <FileText className="h-3 w-3 text-amber-700" />
                        {id}
                      </button>
                    ) : (
                      <code key={id} className="rounded bg-amber-100 px-1.5 py-0.5 font-mono text-[11px] text-amber-900 border border-amber-200 font-semibold">{id}</code>
                    )
                  })}
                </div>
              </div>

              {lead.status === 'NEW' ? (
                <div className="mt-5 flex flex-wrap gap-3">
                  <button onClick={() => submit('ACCEPT')} disabled={decide.isPending} data-testid="accept-lead"
                    className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-5 py-2.5 text-sm font-bold text-white transition-colors hover:bg-blue-700 shadow-sm disabled:opacity-50">
                    <ThumbsUp className="h-4 w-4" /> Accept lead
                  </button>
                  <button onClick={() => submit('REJECT')} disabled={decide.isPending} data-testid="reject-lead"
                    className="inline-flex items-center gap-2 rounded-lg border border-red-300 bg-red-50 px-5 py-2.5 text-sm font-bold text-red-800 transition-colors hover:bg-red-100 disabled:opacity-50">
                    <ThumbsDown className="h-4 w-4" /> Reject lead
                  </button>
                  <span className="self-center text-xs text-neutral-600 font-medium">
                    <ShieldCheck className="mr-1 inline h-3.5 w-3.5 text-emerald-600" /> Decision state and audit entry update immediately; nothing auto-escalates.
                  </span>
                </div>
              ) : (
                <p data-testid="lead-decided" className="mt-5 rounded-lg border border-blue-300 bg-blue-50 p-3 text-sm text-blue-950 font-medium shadow-xs">
                  Decision recorded: <strong>{lead.status}</strong> on{' '}
                  {lead.decided_at ? new Date(lead.decided_at).toLocaleString() : '—'} — visible in the audit trail.
                </p>
              )}
              {copilotError && <p role="alert" className="mt-3 text-sm text-red-600 font-semibold">{copilotError}</p>}
            </div>
          </section>

          <section className="rounded-xl border border-neutral-200 bg-white p-5 shadow-sm" aria-label="Copilot explanation">
            <h3 className="flex items-center gap-2 text-sm font-bold text-neutral-900">
              <MessageSquareCode className="h-4 w-4 text-blue-600" /> Copilot — grounded explanation
            </h3>
            <p className="mt-1 text-xs text-neutral-600">Deterministic fallback. Same lead, same evidence; refuses unsupported claims.</p>

            {copilotQuery.isLoading && <p className="mt-4 text-sm text-neutral-600">Grounding answer…</p>}

            {copilotQuery.data && (
              <div className="mt-4 space-y-3" data-testid="copilot-answer">
                {copilotQuery.data.is_refusal ? (
                  <div className="flex items-start gap-2 rounded-lg border border-red-300 bg-red-50 p-3 text-sm text-red-900">
                    <ShieldQuestion className="mt-0.5 h-4 w-4 shrink-0 text-red-600" />
                    {copilotQuery.data.refusal_reason ?? copilotQuery.data.answer}
                  </div>
                ) : (
                  <p className="text-sm leading-relaxed text-neutral-800">{copilotQuery.data.answer}</p>
                )}
                {copilotQuery.data.evidence_ids.length > 0 && (
                  <div className="flex flex-wrap gap-1.5">
                    {copilotQuery.data.evidence_ids.map((id) => (
                      <code key={id} className="rounded bg-amber-100 px-1.5 py-0.5 font-mono text-[11px] text-amber-900 border border-amber-200 font-semibold">{id}</code>
                    ))}
                  </div>
                )}
                {copilotQuery.data.reasoning_path.length > 0 && (
                  <ol className="space-y-1 border-t border-neutral-200 pt-3">
                    {copilotQuery.data.reasoning_path.map((step, i) => (
                      <li key={i} className="font-mono text-[11px] text-neutral-700 font-medium">{i + 1}. {step}</li>
                    ))}
                  </ol>
                )}
              </div>
            )}

            {copilotQuery.isError && (
              <div className="mt-4 flex items-start gap-2 rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900">
                <AlertOctagon className="mt-0.5 h-4 w-4 shrink-0 text-amber-600" />
                Copilot provider offline — the deterministic connection explainer above still shows the full cited path.
              </div>
            )}
          </section>
        </div>
      )}
      <EvidenceDrawer
        relationshipId={evidenceDrawerEdgeId}
        onClose={() => setEvidenceDrawerEdgeId(null)}
      />
    </div>
  )
}
